server:
    port: 9999
    servlet:
        context-path: /uaa

spring:
    security:
        user:
            password: 1234
        oauth2:
            client:
                registration:
                    clientId: acme
                    clientSecret: acmesecret
                    authorized-grant-types: authorization_code,refresh_token,password
                    scope: openid
