spring:
  session:
    store-type: redis
  security:
    user:
      password: "1234"
zuul:
  routes:
    resource:
      path: /resource/**
      url: http://localhost:9000
      sensitive-headers:
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework:
      security: DEBUG
      session: TRACE
